### PR TITLE
Retry reading RTDE interface when unexpected messages appear during s…

### LINKED ISSUE #185: Thread 1 "ur_robot_driver" received signal SIGSEGV, Segmentation fault.
# Summary

Launching
```
roslaunch ur_robot_driver ur10_bringup.launch robot_ip:=10.31.1.70 \
kinematics_config:="${HOME}/left_ur_calibration.yaml" debug:=true
```
display
```shell
Thread 1 "ur_robot_driver" received signal SIGSEGV, Segmentation fault.
ur_driver::rtde_interface::RTDEClient::negotiateProtocolVersion (this=this@entry=0x55555585c9f0)
    at /home/gaetan/ur_ws/src/Universal_Robots_ROS_Driver/ur_robot_driver/src/rtde/rtde_client.cpp:87
87	  if (!tmp_version->accepted_)
```
and then quit due to missing required process.

# Version
 - ROS Driver version: commit 8d8e909554323d1d54ca2b141782a7e0184569b7
 - Affected Robot Software Version(s): Polyscope 3.13

# Impact

Cannot control robot

# Issue details

## Use Case and Setup

UR10 CB3.1 Series with default Polyscope version 3.2.21545 upgrading with a new USB key with version 3.13 on it

## Actual Behavior

Segfault then quit due to missing required process

Moreover, launching
```
roslaunch ur_calibration calibration_correction.launch robot_ip:=10.31.1.70 \
target_filename:="${HOME}/left_ur_calibration.yaml"
```
works but says
```
[DEBUG]: Invalid robot package type recieved: 24
[DEBUG]: Invalid robot package type recieved: 23
[DEBUG]: Invalid robot package type recieved: 5
```
cannot say if this is linked or not

### PR DESCRIPTION
**Pull request by fmauch**
…tartup

At startup we make a couple of requests to the RTDE interface. If the interface
publishes messages by itself, a simple read() from the interface might grab another
message than the answer.

This change checks whether an answer to our requests was received and reports
a warning otherwise while retrying.

For example, this was raised inside #185 

Closes #185

### CODE REVIEW

File: ur_robot_driver/src/rtde/rtde_client.cpp [hunk 1]
```diff
@@ -70,56 +81,77 @@ bool RTDEClient::init()
...
+      // Reset the num_tries variable in case we have to try with another protocol version.
+      num_retries = 0;
+      return tmp_version->accepted_;
+    }
+    else
+    {
+      std::stringstream ss;
+      ss << "Did not receive protocol negotiation answer from robot. Message received instead: " << std::endl
+         << package->toString() << ". Retrying...";
+      LOG_WARN("%s", ss.str().c_str());
```
Comment (gavanderhoorn) [inline ur_robot_driver/src/rtde/rtde_client.cpp:116]: Nice, I was going to suggest doing this 👍

File: ur_robot_driver/src/rtde/rtde_client.cpp [hunk 2]
```diff
@@ -70,56 +81,77 @@ bool RTDEClient::init()
...
     }
   }
-  return protocol_version;
+  throw UrException("Could not negotiate RTDE protocol version after %u tries. Please check the output of the "
+                    "negotiation attempts above to get a hint what could be wrong.");
```
Comment (gavanderhoorn) [inline ur_robot_driver/src/rtde/rtde_client.cpp:120]: The `%u` seems to not be used here?

File: ur_robot_driver/src/rtde/rtde_client.cpp [hunk 3]
```diff
@@ -70,56 +81,77 @@ bool RTDEClient::init()
...
+    {
+      std::stringstream ss;
+      ss << "Did not receive protocol negotiation answer from robot. Message received instead: " << std::endl
+         << package->toString() << ". Retrying...";
+      LOG_WARN("%s", ss.str().c_str());
+    }
   }
-  urcontrol_version_ = tmp_urcontrol_version->version_information_;
+  throw UrException("Could not query urcontrol version after %u tries. Please check the output of the "
+                    "query attempts above to get a hint what could be wrong.");
```
Comment (gavanderhoorn) [inline ur_robot_driver/src/rtde/rtde_client.cpp:154]: Same here with `%u`.

**Comment by fmauch** [comment]
I should really get used to marking my PRs WIP or push later...
